name: home-lab

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-home-lab
    hostname: ansible-home-lab
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - ..:/workspaces/home-lab:cached
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - home-lab

networks:
  home-lab:
    name: home-lab
    driver: bridge
