services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-dev
    hostname: ansible-dev
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - ..:/workspaces/ansible-dev:cached
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - ansible-dev

networks:
  ansible-dev:
    name: ansible-dev
    driver: bridge
